### ISSUE TITLE
How to install rust-based plugin, e.g. ripgrep

### ISSUE THREAD

**Issue by yanxiang-wang** [rossmacarthur/sheldon#169] opened 2023-12-12 23:32 UTC
This is a good tool. However, I don't how to install some plugins.
https://github.com/BurntSushi/ripgrep
Also the other tools in https://github.com/ibraheemdev/modern-unix.

**Comment by rossmacarthur** [comment] 2024-01-26 15:18
This is a duplicate of #132

**Closed as completed by rossmacarthur** 2024-01-26 15:18 UTC
Labels: feature
